### ISSUE TITLE
trunc2norm requires both min and max values

### ISSUE THREAD

**Issue by elctrc** [debruine/faux#36]
If you attempt to run `trunc2norm` with the default values for min and max you receive the following error:

```
Error in truncnorm::ptruncnorm(x, a = min, b = max, mean = mu, sd = sd) : 
  promise already under evaluation: recursive default argument reference or earlier problems?
```
Using the example from the vignette (without the parameters) will generate the error:
```
x <- truncnorm::rtruncnorm(10000, 1, 7, 3.5, 2)
y <- trunc2norm(x)
```
If you attempt to declare just min or just max parameters (and not both) you will receive the error.

In addition, when I attempted to run with both min/max included with a min of 0, I still received values at -Inf in return.

Sample usage that generated the -Inf values below, where df is a data.frame of numeric values:
`df_trunc <- as.data.frame(sapply(df, trunc2norm, min = 0, max = 4))`

https://github.com/debruine/faux/blob/a5e914b178b6b66d40c30460d41d43b7b8ee2f8b/R/distribution_convertors.R#L147

p.s. This is a wonderful R package!! Thank you for making it.

**Comment by debruine** [comment]
I'm fixing this now to set min and max to 3 SD below and above the mean (calculated from x if those aren't set). If the min or max values in x are outside this range, the min or max are reset to the min or max of x, minus or plus 0.1 SD (otherwise they convert to +/-Inf). Does this make sense? Probably anyone using this function will manually set the min and max, but it makes some reasonable assumptions if not.

**Comment by elctrc** [comment]
That does make sense! I think it is a solid solution.
